### ISSUE TITLE
About the chat template of llama3-instruct

### ISSUE THREAD

**Issue by chchch0109** [rishub-tamirisa/tamper-resistance#10]
Hi,
Thanks for releasing this interesting work! I want to ask for the llama3-instruct's chat template, why do you only use it in hh_rlhf dataset and and magpie dataset but not in all datasets? I suppose all fine-tuning datasets should follow the chat template by default. Thanks!

**Comment by rishub-tamirisa** [comment]
Hello, our forget datasets come from raw-text document datasets, e.g. the Pile. Since they aren't user-assistant conversation data, it wouldn't make sense to wrap the text chunks in a conversation template, as we don't have examples of model responses to those text chunks.

Generally instruction-tuned models can be still fine-tuned on raw-text to introduce new knowledge without affecting chat capabilities, but we found that including the `magpie` dataset as an additional retain set helped stabilize chat performance after TAR.
